server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rent_auth_db?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: never
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    format_sql: true